CREATE TABLE IF NOT EXISTS user_sessions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_name TEXT NOT NULL,
    ip TEXT NOT NULL,
    time_started TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    time_ended TIMESTAMPTZ,
    kicked_off BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_session_id BIGINT NOT NULL REFERENCES user_sessions(id),
    message TEXT NOT NULL,
    time_sent TIMESTAMPTZ NOT NULL
);
